[package]
name = "cloud-atlas"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.25"
neo4rs = "0.5.9"
tokio = { version = "1.21.2", features = ["full"] }
uuid = { version = "1.2.1", features = ["v4"] }
aws-config = "0.49.0"
aws-sdk-config = "0.19.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
clap = { version = "4.0.17", features = ["derive", "unicode"] }
aws-sdk-ec2 = "0.19.0"
aws-types = "0.49.0"
petgraph = "0.6"
