[package]
name = "aws-explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.23"
neo4rs = "0.5.9"
tokio = {version="1.20.1", features=["full"]}
uuid = {version="1.1.2", features=["v4"]}
aws-config = "0.47"
aws-sdk-config = "0.17"
structopt = "0.3"
tracing-subscriber = {version="0.3.5", features = ["env-filter"]}
