[package]
name = "aws-explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.23"
neo4rs = "0.5.9"
tokio = "1.20.1"
uuid = {version="1.1.2", features=["v4"]}
